/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ranalyzer;

import java.io.*;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.*;
import javax.swing.DefaultListModel;
import javax.swing.JFileChooser;
import javax.swing.SwingUtilities;
import javax.swing.event.*;

/**
 *
 * @author 5115100168
 */
public class ProjectWorksheet extends javax.swing.JFrame {

    /**
     * Creates new form ProjectWorksheet
     */
    Project project = null;
    String projectName;
    DefaultListModel model = new DefaultListModel();
    DefaultListModel statementLstModel = new DefaultListModel();
    String tmpStatName;
    DocumentController documentController;
    ProjectController projectController;
    ExistingProjectController existingProjectController;
    StatementController statementController;
    DependencyController dependencyController;
    
    public ProjectWorksheet() {
        initComponents();
        changeEnable(false);
        documentController = new DocumentController(this);
        projectController = new ProjectController(this);
        existingProjectController = new ExistingProjectController(this);
        statementController = new StatementController(this);
        dependencyController = new DependencyController(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        projectOpener = new javax.swing.JFileChooser();
        documentOpener = new javax.swing.JFileChooser();
        projectCreator = new javax.swing.JFileChooser();
        deleteDocConfirmation = new javax.swing.JDialog();
        deleteDocYes = new javax.swing.JButton();
        deleteDocNo = new javax.swing.JButton();
        confirmMessage = new javax.swing.JLabel();
        noDocumentSelected = new javax.swing.JDialog();
        failMessage = new javax.swing.JLabel();
        loadingDialog = new javax.swing.JDialog();
        loadingBar = new javax.swing.JProgressBar();
        jLabel2 = new javax.swing.JLabel();
        documentDescriptionWindow = new javax.swing.JDialog();
        useCaseDescriptionLabel = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        useCaseDescriptionContent = new javax.swing.JTextArea();
        submitDocumentDescription = new javax.swing.JButton();
        progressInformation = new javax.swing.JDialog();
        progressBar = new javax.swing.JProgressBar();
        jLabel3 = new javax.swing.JLabel();
        addStatementWindow = new javax.swing.JDialog();
        jScrollPane4 = new javax.swing.JScrollPane();
        newStatementContent = new javax.swing.JTextArea();
        newStatementAdd = new javax.swing.JButton();
        newStatementName = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        deleteStatementConfirmation = new javax.swing.JDialog();
        deleteStatementYes = new javax.swing.JButton();
        deleteStatementNo = new javax.swing.JButton();
        confirmDeleteStatementMessage = new javax.swing.JLabel();
        editStatementWindow = new javax.swing.JDialog();
        jScrollPane7 = new javax.swing.JScrollPane();
        editStatementContentTxt = new javax.swing.JTextArea();
        editStatementSave = new javax.swing.JButton();
        editStatementNameTxt = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        projectDescriptionWindow = new javax.swing.JDialog();
        newProjectNameTxt = new javax.swing.JTextField();
        jScrollPane8 = new javax.swing.JScrollPane();
        newProjectDescriptionTxt = new javax.swing.JTextArea();
        newProjectDirectoryTxt = new javax.swing.JTextField();
        selectNewProjectDirectoryBtn = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        newProjectContinueBtn = new javax.swing.JButton();
        newProjectDirectoryChooser = new javax.swing.JFileChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        docList = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        documentContent = new javax.swing.JTextArea();
        documentPanel = new javax.swing.JPanel();
        addDocumentBtn = new javax.swing.JButton();
        deleteDocumentBtn = new javax.swing.JButton();
        addDescriptionButton = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        deleteStatementBtn = new javax.swing.JButton();
        addStatementBtn = new javax.swing.JButton();
        editStatementBtn = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        checkDependencyBtn = new javax.swing.JButton();
        viewDependencyBtn = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        statementList = new javax.swing.JList<>();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        statementContent = new javax.swing.JTextArea();
        jMenuBar1 = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        openProjectItem = new javax.swing.JMenuItem();
        createNewProjectMenuItem = new javax.swing.JMenuItem();
        saveProjectMenuItem = new javax.swing.JMenuItem();
        closeProjectMenuItem = new javax.swing.JMenuItem();

        projectOpener.setFileFilter(new MyCustomFilter());
        projectOpener.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                projectOpenerActionPerformed(evt);
            }
        });

        documentOpener.setFileFilter(new XMLFilter());

        projectCreator.setDialogTitle("Create new project");
        projectCreator.setFileFilter(new MyCustomFilter());

        deleteDocConfirmation.setTitle("Remove document");
        deleteDocConfirmation.setMinimumSize(new java.awt.Dimension(500, 300));
        deleteDocConfirmation.setModalityType(java.awt.Dialog.ModalityType.DOCUMENT_MODAL);

        deleteDocYes.setText("Yes");
        deleteDocYes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteDocYesActionPerformed(evt);
            }
        });

        deleteDocNo.setText("No");
        deleteDocNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteDocNoActionPerformed(evt);
            }
        });

        confirmMessage.setLabelFor(deleteDocConfirmation);

        javax.swing.GroupLayout deleteDocConfirmationLayout = new javax.swing.GroupLayout(deleteDocConfirmation.getContentPane());
        deleteDocConfirmation.getContentPane().setLayout(deleteDocConfirmationLayout);
        deleteDocConfirmationLayout.setHorizontalGroup(
            deleteDocConfirmationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(deleteDocConfirmationLayout.createSequentialGroup()
                .addGroup(deleteDocConfirmationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(deleteDocConfirmationLayout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(confirmMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(deleteDocConfirmationLayout.createSequentialGroup()
                        .addGap(127, 127, 127)
                        .addComponent(deleteDocYes, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(deleteDocNo, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        deleteDocConfirmationLayout.setVerticalGroup(
            deleteDocConfirmationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, deleteDocConfirmationLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(confirmMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(deleteDocConfirmationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(deleteDocNo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(deleteDocYes, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25))
        );

        javax.swing.GroupLayout noDocumentSelectedLayout = new javax.swing.GroupLayout(noDocumentSelected.getContentPane());
        noDocumentSelected.getContentPane().setLayout(noDocumentSelectedLayout);
        noDocumentSelectedLayout.setHorizontalGroup(
            noDocumentSelectedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(noDocumentSelectedLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(failMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(48, Short.MAX_VALUE))
        );
        noDocumentSelectedLayout.setVerticalGroup(
            noDocumentSelectedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(noDocumentSelectedLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(failMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        loadingDialog.setMinimumSize(new java.awt.Dimension(500, 150));
        loadingDialog.setModalityType(java.awt.Dialog.ModalityType.DOCUMENT_MODAL);

        loadingBar.setStringPainted(true);
        loadingBar.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                loadingBarPropertyChange(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Opening document");

        javax.swing.GroupLayout loadingDialogLayout = new javax.swing.GroupLayout(loadingDialog.getContentPane());
        loadingDialog.getContentPane().setLayout(loadingDialogLayout);
        loadingDialogLayout.setHorizontalGroup(
            loadingDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loadingDialogLayout.createSequentialGroup()
                .addGroup(loadingDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(loadingDialogLayout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(loadingBar, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(loadingDialogLayout.createSequentialGroup()
                        .addGap(124, 124, 124)
                        .addComponent(jLabel2)))
                .addContainerGap(52, Short.MAX_VALUE))
        );
        loadingDialogLayout.setVerticalGroup(
            loadingDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loadingDialogLayout.createSequentialGroup()
                .addContainerGap(44, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(42, 42, 42)
                .addComponent(loadingBar, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
        );

        documentDescriptionWindow.setTitle("Use Case Description");
        documentDescriptionWindow.setMinimumSize(new java.awt.Dimension(654, 400));

        useCaseDescriptionContent.setColumns(20);
        useCaseDescriptionContent.setRows(5);
        jScrollPane3.setViewportView(useCaseDescriptionContent);

        submitDocumentDescription.setText("Submit");
        submitDocumentDescription.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitDocumentDescriptionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout documentDescriptionWindowLayout = new javax.swing.GroupLayout(documentDescriptionWindow.getContentPane());
        documentDescriptionWindow.getContentPane().setLayout(documentDescriptionWindowLayout);
        documentDescriptionWindowLayout.setHorizontalGroup(
            documentDescriptionWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(documentDescriptionWindowLayout.createSequentialGroup()
                .addGroup(documentDescriptionWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(documentDescriptionWindowLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(submitDocumentDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, documentDescriptionWindowLayout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(documentDescriptionWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(useCaseDescriptionLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 569, Short.MAX_VALUE))))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        documentDescriptionWindowLayout.setVerticalGroup(
            documentDescriptionWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(documentDescriptionWindowLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(useCaseDescriptionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(submitDocumentDescription, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)
                .addContainerGap())
        );

        progressInformation.setMinimumSize(new java.awt.Dimension(500, 150));
        progressInformation.setModalityType(java.awt.Dialog.ModalityType.DOCUMENT_MODAL);

        progressBar.setStringPainted(true);
        progressBar.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                progressBarPropertyChange(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Saving description");

        javax.swing.GroupLayout progressInformationLayout = new javax.swing.GroupLayout(progressInformation.getContentPane());
        progressInformation.getContentPane().setLayout(progressInformationLayout);
        progressInformationLayout.setHorizontalGroup(
            progressInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(progressInformationLayout.createSequentialGroup()
                .addGroup(progressInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(progressInformationLayout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(progressBar, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(progressInformationLayout.createSequentialGroup()
                        .addGap(124, 124, 124)
                        .addComponent(jLabel3)))
                .addContainerGap(52, Short.MAX_VALUE))
        );
        progressInformationLayout.setVerticalGroup(
            progressInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, progressInformationLayout.createSequentialGroup()
                .addContainerGap(44, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(42, 42, 42)
                .addComponent(progressBar, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
        );

        addStatementWindow.setTitle("Add new statement");
        addStatementWindow.setMinimumSize(new java.awt.Dimension(700, 300));
        addStatementWindow.setModalityType(java.awt.Dialog.ModalityType.DOCUMENT_MODAL);

        newStatementContent.setColumns(20);
        newStatementContent.setRows(5);
        jScrollPane4.setViewportView(newStatementContent);

        newStatementAdd.setText("Add");
        newStatementAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newStatementAddActionPerformed(evt);
            }
        });

        jLabel4.setText("Statement name");

        jLabel6.setText("Statement content");

        javax.swing.GroupLayout addStatementWindowLayout = new javax.swing.GroupLayout(addStatementWindow.getContentPane());
        addStatementWindow.getContentPane().setLayout(addStatementWindowLayout);
        addStatementWindowLayout.setHorizontalGroup(
            addStatementWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addStatementWindowLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(addStatementWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(addStatementWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(newStatementName)
                    .addComponent(newStatementAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        addStatementWindowLayout.setVerticalGroup(
            addStatementWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addStatementWindowLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(addStatementWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(newStatementName, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(addStatementWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(addStatementWindowLayout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(jLabel6)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(newStatementAdd, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                .addContainerGap())
        );

        deleteStatementConfirmation.setTitle("Remove statement");
        deleteStatementConfirmation.setMinimumSize(new java.awt.Dimension(500, 300));
        deleteStatementConfirmation.setModalityType(java.awt.Dialog.ModalityType.DOCUMENT_MODAL);

        deleteStatementYes.setText("Yes");
        deleteStatementYes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteStatementYesActionPerformed(evt);
            }
        });

        deleteStatementNo.setText("No");
        deleteStatementNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteStatementNoActionPerformed(evt);
            }
        });

        confirmDeleteStatementMessage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        confirmDeleteStatementMessage.setLabelFor(deleteDocConfirmation);

        javax.swing.GroupLayout deleteStatementConfirmationLayout = new javax.swing.GroupLayout(deleteStatementConfirmation.getContentPane());
        deleteStatementConfirmation.getContentPane().setLayout(deleteStatementConfirmationLayout);
        deleteStatementConfirmationLayout.setHorizontalGroup(
            deleteStatementConfirmationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(deleteStatementConfirmationLayout.createSequentialGroup()
                .addGroup(deleteStatementConfirmationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(deleteStatementConfirmationLayout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(confirmDeleteStatementMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(deleteStatementConfirmationLayout.createSequentialGroup()
                        .addGap(127, 127, 127)
                        .addComponent(deleteStatementYes, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(deleteStatementNo, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(75, Short.MAX_VALUE))
        );
        deleteStatementConfirmationLayout.setVerticalGroup(
            deleteStatementConfirmationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, deleteStatementConfirmationLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(confirmDeleteStatementMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addGroup(deleteStatementConfirmationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(deleteStatementNo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(deleteStatementYes, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25))
        );

        editStatementWindow.setTitle("Edit statement");
        editStatementWindow.setMinimumSize(new java.awt.Dimension(700, 300));
        editStatementWindow.setModalityType(java.awt.Dialog.ModalityType.DOCUMENT_MODAL);

        editStatementContentTxt.setColumns(20);
        editStatementContentTxt.setRows(5);
        jScrollPane7.setViewportView(editStatementContentTxt);

        editStatementSave.setText("Save");
        editStatementSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editStatementSaveActionPerformed(evt);
            }
        });

        jLabel7.setText("Statement name");

        jLabel8.setText("Statement content");

        javax.swing.GroupLayout editStatementWindowLayout = new javax.swing.GroupLayout(editStatementWindow.getContentPane());
        editStatementWindow.getContentPane().setLayout(editStatementWindowLayout);
        editStatementWindowLayout.setHorizontalGroup(
            editStatementWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editStatementWindowLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(editStatementWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(editStatementWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(editStatementNameTxt)
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, editStatementWindowLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(editStatementSave, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        editStatementWindowLayout.setVerticalGroup(
            editStatementWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editStatementWindowLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(editStatementWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(editStatementNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(35, 35, 35)
                .addGroup(editStatementWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(editStatementWindowLayout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(jLabel8)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(editStatementSave, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(15, 15, 15))
        );

        projectDescriptionWindow.setTitle("Project Description Window");
        projectDescriptionWindow.setMinimumSize(new java.awt.Dimension(786, 480));
        projectDescriptionWindow.setModalityType(java.awt.Dialog.ModalityType.DOCUMENT_MODAL);

        newProjectNameTxt.setText("Untitled");

        newProjectDescriptionTxt.setColumns(20);
        newProjectDescriptionTxt.setRows(5);
        jScrollPane8.setViewportView(newProjectDescriptionTxt);

        selectNewProjectDirectoryBtn.setText("...");
        selectNewProjectDirectoryBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectNewProjectDirectoryBtnActionPerformed(evt);
            }
        });

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("Name");

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel10.setText("Location");

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel11.setText("Description");

        newProjectContinueBtn.setText("Continue");
        newProjectContinueBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newProjectContinueBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout projectDescriptionWindowLayout = new javax.swing.GroupLayout(projectDescriptionWindow.getContentPane());
        projectDescriptionWindow.getContentPane().setLayout(projectDescriptionWindowLayout);
        projectDescriptionWindowLayout.setHorizontalGroup(
            projectDescriptionWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, projectDescriptionWindowLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(newProjectContinueBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
            .addGroup(projectDescriptionWindowLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(projectDescriptionWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(projectDescriptionWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane8)
                    .addComponent(newProjectNameTxt)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, projectDescriptionWindowLayout.createSequentialGroup()
                        .addComponent(newProjectDirectoryTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 484, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(selectNewProjectDirectoryBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(46, Short.MAX_VALUE))
        );
        projectDescriptionWindowLayout.setVerticalGroup(
            projectDescriptionWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(projectDescriptionWindowLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(projectDescriptionWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(newProjectNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(projectDescriptionWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(selectNewProjectDirectoryBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(newProjectDirectoryTxt)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(projectDescriptionWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane8)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(newProjectContinueBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                .addContainerGap())
        );

        newProjectDirectoryChooser.setDialogTitle("Select project directory");
        newProjectDirectoryChooser.setFileSelectionMode(javax.swing.JFileChooser.DIRECTORIES_ONLY);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Requirement Analyzer");
        setResizable(false);

        docList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        docList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                docListValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(docList);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Statement List");
        jLabel1.setToolTipText("");

        documentContent.setEditable(false);
        documentContent.setColumns(20);
        documentContent.setRows(5);
        documentContent.setAutoscrolls(false);
        jScrollPane2.setViewportView(documentContent);

        documentPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Document"));

        addDocumentBtn.setText("Add Document");
        addDocumentBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addDocumentBtnActionPerformed(evt);
            }
        });

        deleteDocumentBtn.setText("Delete Document");
        deleteDocumentBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteDocumentBtnActionPerformed(evt);
            }
        });

        addDescriptionButton.setText("Add Description");
        addDescriptionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addDescriptionButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout documentPanelLayout = new javax.swing.GroupLayout(documentPanel);
        documentPanel.setLayout(documentPanelLayout);
        documentPanelLayout.setHorizontalGroup(
            documentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(documentPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(documentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(deleteDocumentBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 242, Short.MAX_VALUE)
                    .addComponent(addDocumentBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(addDescriptionButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        documentPanelLayout.setVerticalGroup(
            documentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(documentPanelLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(addDocumentBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(deleteDocumentBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addDescriptionButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(77, Short.MAX_VALUE))
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Statement"));

        deleteStatementBtn.setText("Delete Statement");
        deleteStatementBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteStatementBtnActionPerformed(evt);
            }
        });

        addStatementBtn.setText("Add Statement");
        addStatementBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addStatementBtnActionPerformed(evt);
            }
        });

        editStatementBtn.setText("Edit Statement");
        editStatementBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editStatementBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(41, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(editStatementBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addStatementBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deleteStatementBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(addStatementBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(editStatementBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(deleteStatementBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Dependency"));

        checkDependencyBtn.setText("Check Dependency");

        viewDependencyBtn.setText("View Dependency");
        viewDependencyBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewDependencyBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(55, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(viewDependencyBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(checkDependencyBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addComponent(checkDependencyBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(viewDependencyBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );

        statementList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                statementListValueChanged(evt);
            }
        });
        jScrollPane5.setViewportView(statementList);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Use Case Diagram List");
        jLabel5.setToolTipText("");

        statementContent.setEditable(false);
        statementContent.setColumns(20);
        statementContent.setRows(5);
        jScrollPane6.setViewportView(statementContent);

        fileMenu.setText("File");

        openProjectItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        openProjectItem.setText("Open project");
        openProjectItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openProjectItemActionPerformed(evt);
            }
        });
        fileMenu.add(openProjectItem);

        createNewProjectMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        createNewProjectMenuItem.setText("Create new project");
        createNewProjectMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createNewProjectMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(createNewProjectMenuItem);

        saveProjectMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        saveProjectMenuItem.setText("Save project");
        saveProjectMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveProjectMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(saveProjectMenuItem);

        closeProjectMenuItem.setText("Close project");
        closeProjectMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeProjectMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(closeProjectMenuItem);

        jMenuBar1.add(fileMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 326, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(documentPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 409, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(161, 161, 161)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(documentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 232, Short.MAX_VALUE)
                            .addComponent(jScrollPane6))
                        .addGap(18, 18, 18)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void openProjectItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openProjectItemActionPerformed
        this.existingProjectController.showProjectDescriptionWindow(this.projectOpener);
    }//GEN-LAST:event_openProjectItemActionPerformed

    private void projectOpenerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_projectOpenerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_projectOpenerActionPerformed

    private void createNewProjectMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createNewProjectMenuItemActionPerformed
        this.projectController.showProjectDescriptionWindow(this.projectDescriptionWindow);
    }//GEN-LAST:event_createNewProjectMenuItemActionPerformed

    private void saveProjectMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveProjectMenuItemActionPerformed
        this.project.save(project, projectName);
    }//GEN-LAST:event_saveProjectMenuItemActionPerformed

    private void docListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_docListValueChanged
        String namaFile = this.docList.getSelectedValue();
        
        for(final RequirementDocument i: project.docList){
            if(i.Nama_document.equals(namaFile)){
                this.documentContent.setText(i.getContent());
                this.documentContent.append("Description:\n" + i.deskripsi);
                break;
            }
        }
    }//GEN-LAST:event_docListValueChanged

    private void deleteDocYesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteDocYesActionPerformed
        String fileName = this.docList.getSelectedValue();
        
        int index = this.docList.getSelectedIndex();
        
        this.documentController.deleteDocument(fileName, index);
        
        this.documentContent.setText("");
        this.deleteDocConfirmation.setEnabled(false);
        this.deleteDocConfirmation.setVisible(false);
        
    }//GEN-LAST:event_deleteDocYesActionPerformed

    private void deleteDocNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteDocNoActionPerformed
        this.deleteDocConfirmation.setVisible(false);
        this.deleteDocConfirmation.setEnabled(false);
    }//GEN-LAST:event_deleteDocNoActionPerformed

    private void closeProjectMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeProjectMenuItemActionPerformed
        this.project = null;
        this.model.clear();
        this.docList.setEnabled(false);
        this.documentContent.setText("");
        this.documentContent.setEnabled(false);
        this.changeEnable(false);
        this.setTitle("Requirement Analyzer");
    }//GEN-LAST:event_closeProjectMenuItemActionPerformed

    private void addDocumentBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addDocumentBtnActionPerformed
        this.documentController.openFileExplorer(this.documentOpener, this.loadingDialog, this.loadingBar);
        this.docList.setModel(model);
    }//GEN-LAST:event_addDocumentBtnActionPerformed

    private void deleteDocumentBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteDocumentBtnActionPerformed
        String fileName = this.docList.getSelectedValue();
        
        this.documentController.showDeleteConfirmation(fileName, this.confirmMessage, this.deleteDocConfirmation);
    }//GEN-LAST:event_deleteDocumentBtnActionPerformed

    private void loadingBarPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_loadingBarPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_loadingBarPropertyChange

    private void addDescriptionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addDescriptionButtonActionPerformed

        this.documentController.loadUseCaseDescriptionForm(this.docList.getSelectedValue(), this.useCaseDescriptionLabel, this.documentDescriptionWindow);
        
    }//GEN-LAST:event_addDescriptionButtonActionPerformed

    private void submitDocumentDescriptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitDocumentDescriptionActionPerformed
        String desc = this.useCaseDescriptionContent.getText();
        
        this.documentController.submitUseCaseDescription(desc, this.docList, this.progressInformation, this.progressBar);
        
        this.useCaseDescriptionContent.setText("");
        this.documentDescriptionWindow.setEnabled(false);
        this.documentDescriptionWindow.setVisible(false);
    }//GEN-LAST:event_submitDocumentDescriptionActionPerformed

    private void progressBarPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_progressBarPropertyChange

    }//GEN-LAST:event_progressBarPropertyChange

    private void addStatementBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addStatementBtnActionPerformed
        this.statementController.showStatementForm(this.addStatementWindow);
    }//GEN-LAST:event_addStatementBtnActionPerformed

    private void newStatementAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newStatementAddActionPerformed
        String nama = this.newStatementName.getText();
        String content = this.newStatementContent.getText();
        
        this.statementController.storeStatement(nama, content);

        this.newStatementName.setText("");
        this.newStatementContent.setText("");
    }//GEN-LAST:event_newStatementAddActionPerformed

    private void statementListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_statementListValueChanged
        String namaStatement = this.statementList.getSelectedValue();
        
        for(final Statement i: this.project.statementList){
            if(i.Nama_statement.equals(namaStatement)){
                this.statementContent.setText(i.Statement_content);
                break;
            }
        }
    }//GEN-LAST:event_statementListValueChanged

    private void deleteStatementBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteStatementBtnActionPerformed
        String statName = this.statementList.getSelectedValue();
        this.statementController.deleteStatementConfirmation(statName, this.confirmDeleteStatementMessage, this.deleteStatementConfirmation);;
    }//GEN-LAST:event_deleteStatementBtnActionPerformed

    private void deleteStatementYesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteStatementYesActionPerformed

        String statName = this.statementList.getSelectedValue();
        int index = this.statementList.getSelectedIndex();
        
        this.statementController.deleteSelectedStatement(statName, index);
                
        this.statementContent.setText("");
        this.deleteStatementConfirmation.setVisible(false);
        this.deleteStatementConfirmation.setEnabled(false);
    }//GEN-LAST:event_deleteStatementYesActionPerformed

    private void deleteStatementNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteStatementNoActionPerformed
        this.deleteStatementConfirmation.setVisible(false);
        this.deleteStatementConfirmation.setEnabled(false);
    }//GEN-LAST:event_deleteStatementNoActionPerformed

    private void editStatementBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editStatementBtnActionPerformed
        String statName = this.statementList.getSelectedValue();
        String statContent = null;
        
        this.statementController.editStatement(statName, statContent, this.editStatementNameTxt, this.editStatementContentTxt);
        this.editStatementWindow.setEnabled(true);
        this.editStatementWindow.setVisible(true);
    }//GEN-LAST:event_editStatementBtnActionPerformed

    private void editStatementSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editStatementSaveActionPerformed
        String statName = this.statementList.getSelectedValue();
        String statContent = this.statementContent.getText();
        
        this.statementController.storeChangedStatement(statName,statContent, this.editStatementNameTxt.getText(),this.editStatementContentTxt.getText(), statementList);

        this.statementContent.setText(this.editStatementContentTxt.getText());
        this.editStatementWindow.setVisible(false);
        this.editStatementWindow.setEnabled(false);
    }//GEN-LAST:event_editStatementSaveActionPerformed

    private void selectNewProjectDirectoryBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectNewProjectDirectoryBtnActionPerformed
        int returnVal = this.newProjectDirectoryChooser.showOpenDialog(this);
        
        if(returnVal == JFileChooser.APPROVE_OPTION){
            this.newProjectDirectoryTxt.setText(this.newProjectDirectoryChooser.getSelectedFile().getAbsolutePath());
        }
    }//GEN-LAST:event_selectNewProjectDirectoryBtnActionPerformed

    private void newProjectContinueBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newProjectContinueBtnActionPerformed
        this.projectDescriptionWindow.setEnabled(false);
        this.projectDescriptionWindow.setVisible(false);
        
        String name = this.newProjectNameTxt.getText();
        String path = this.newProjectDirectoryTxt.getText();
        String desc = this.newProjectDescriptionTxt.getText();
        
        DateFormat dateFormat = new SimpleDateFormat("yyyy/MM/dd HH:mm:ss");
        Date date = new Date();
        String tgl = dateFormat.format(date);
        
        this.projectController.createNewProject(name, path, desc, tgl);
        
        this.projectName = name;
        
        this.setTitle(projectName);
        
        this.changeEnable(true);
    }//GEN-LAST:event_newProjectContinueBtnActionPerformed

    private void viewDependencyBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewDependencyBtnActionPerformed
        List<Component> components = new ArrayList<Component>();
        List<Statement> statements = new ArrayList<Statement>();
        List<Relation> relationList = new ArrayList<Relation>();
        
        for(final RequirementDocument i: this.project.docList){
            components = i.componentList;
            relationList = i.relationList;
        }
        
        statements = this.project.statementList;
        
        this.dependencyController.checkDependency(components, statements, relationList);
    }//GEN-LAST:event_viewDependencyBtnActionPerformed
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProjectWorksheet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProjectWorksheet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProjectWorksheet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProjectWorksheet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProjectWorksheet().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addDescriptionButton;
    private javax.swing.JButton addDocumentBtn;
    private javax.swing.JButton addStatementBtn;
    private javax.swing.JDialog addStatementWindow;
    private javax.swing.JButton checkDependencyBtn;
    private javax.swing.JMenuItem closeProjectMenuItem;
    private javax.swing.JLabel confirmDeleteStatementMessage;
    private javax.swing.JLabel confirmMessage;
    private javax.swing.JMenuItem createNewProjectMenuItem;
    private javax.swing.JDialog deleteDocConfirmation;
    private javax.swing.JButton deleteDocNo;
    private javax.swing.JButton deleteDocYes;
    private javax.swing.JButton deleteDocumentBtn;
    private javax.swing.JButton deleteStatementBtn;
    private javax.swing.JDialog deleteStatementConfirmation;
    private javax.swing.JButton deleteStatementNo;
    private javax.swing.JButton deleteStatementYes;
    private javax.swing.JList<String> docList;
    private javax.swing.JTextArea documentContent;
    private javax.swing.JDialog documentDescriptionWindow;
    private javax.swing.JFileChooser documentOpener;
    private javax.swing.JPanel documentPanel;
    private javax.swing.JButton editStatementBtn;
    private javax.swing.JTextArea editStatementContentTxt;
    private javax.swing.JTextField editStatementNameTxt;
    private javax.swing.JButton editStatementSave;
    private javax.swing.JDialog editStatementWindow;
    private javax.swing.JLabel failMessage;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JProgressBar loadingBar;
    private javax.swing.JDialog loadingDialog;
    private javax.swing.JButton newProjectContinueBtn;
    private javax.swing.JTextArea newProjectDescriptionTxt;
    private javax.swing.JFileChooser newProjectDirectoryChooser;
    private javax.swing.JTextField newProjectDirectoryTxt;
    private javax.swing.JTextField newProjectNameTxt;
    private javax.swing.JButton newStatementAdd;
    private javax.swing.JTextArea newStatementContent;
    private javax.swing.JTextField newStatementName;
    private javax.swing.JDialog noDocumentSelected;
    private javax.swing.JMenuItem openProjectItem;
    private javax.swing.JProgressBar progressBar;
    private javax.swing.JDialog progressInformation;
    private javax.swing.JFileChooser projectCreator;
    private javax.swing.JDialog projectDescriptionWindow;
    private javax.swing.JFileChooser projectOpener;
    private javax.swing.JMenuItem saveProjectMenuItem;
    private javax.swing.JButton selectNewProjectDirectoryBtn;
    private javax.swing.JTextArea statementContent;
    private javax.swing.JList<String> statementList;
    private javax.swing.JButton submitDocumentDescription;
    private javax.swing.JTextArea useCaseDescriptionContent;
    private javax.swing.JLabel useCaseDescriptionLabel;
    private javax.swing.JButton viewDependencyBtn;
    // End of variables declaration//GEN-END:variables
    
    public JFileChooser getDocumentOpener(){
        return this.documentOpener;
    }
    
    private static class MyCustomFilter extends javax.swing.filechooser.FileFilter {
        @Override
        public boolean accept(File file) {
            // Allow only directories, or files with ".txt" extension
            return file.isDirectory() || file.getAbsolutePath().endsWith(".ran");
        }
        @Override
        public String getDescription() {
            // This description will be displayed in the dialog,
            // hard-coded = ugly, should be done via I18N
            return "Requirements Analyzer File (*.ran)";
        }
    }

    private static class XMLFilter extends javax.swing.filechooser.FileFilter {
        @Override
        public boolean accept(File file) {
            // Allow only directories, or files with ".txt" extension
            return file.isDirectory() || file.getAbsolutePath().endsWith(".xmi");
        }
        @Override
        public String getDescription() {
            // This description will be displayed in the dialog,
            // hard-coded = ugly, should be done via I18N
            return "XML Metadata Interchange (*.xmi)";
        }
    }
    
    public void enable(){
        this.setTitle(projectName);
        this.documentContent.setEnabled(true);
        this.docList.setEnabled(true);
        this.saveProjectMenuItem.setEnabled(true);
        this.closeProjectMenuItem.setEnabled(true);

    }
    
    public void initListDoc(){
        for(final RequirementDocument i: project.docList){
            model.addElement(i.Nama_document);
        }
        
        this.docList.setModel(model);
    }
    
    public void initListStatement(){
        for(final Statement i: project.statementList){
            this.statementLstModel.addElement(i.Nama_statement);
        }
        
        this.statementList.setModel(statementLstModel);
    }
    
    public void changeEnable(Boolean params){
        this.documentContent.setEnabled(params);
        this.docList.setEnabled(params);
        this.saveProjectMenuItem.setEnabled(params);
        this.closeProjectMenuItem.setEnabled(params);
        this.addDocumentBtn.setEnabled(params);
        this.deleteDocumentBtn.setEnabled(params);
        this.addStatementBtn.setEnabled(params);
        this.deleteStatementBtn.setEnabled(params);
        this.editStatementBtn.setEnabled(params);
        this.viewDependencyBtn.setEnabled(params);
        this.checkDependencyBtn.setEnabled(params);
        this.addDescriptionButton.setEnabled(params);
    }
    
    private class ProgressTask extends Thread{
        public ProgressTask(){
            
        }
        
        public void run(){
            for(int i = 0; i <= 100; i++){
                final int progress = i;
                
                SwingUtilities.invokeLater(new Runnable(){
                    public void run(){
                        progressBar.setValue(progress);
                    }
                });
                try {
                    Thread.sleep(5);
                 } catch (InterruptedException e) {}
            }
            
            dismissProgressDialog();
        }
    }
    
    public void dismissProgressDialog(){
        this.progressBar.setEnabled(false);
        this.progressBar.setVisible(false);
        
        this.progressInformation.setEnabled(false);
        this.progressInformation.setVisible(false);
    }
}

